### ISSUE TITLE
[Feature] Don't grey while playing 

### ISSUE THREAD

**Issue by klauf** [brarcher/baby-sleep-sounds#40] opened 2017-07-23 21:38 UTC
Hi
Thanks a lot for this very useful app, from a father with 5 months experience :) 
I noticed that once 'play' is pressed, the sound and sleep timer are greyed out and can't be modified until 'stop' is pressed. 
Is there a reason for that? Would it be possible to keep them both active? 
Cheers

**Comment by brarcher** [comment] 2017-07-24 03:11
I'm glad that you have found the app useful. (:

As for the greying out, some background. This application was intended to be a simple, no frills, white noise generator. The simplest implementation I could come up with involved setting up what should be played, then playing it over and over until it should stop. There was no thought for the ability to change the playback midstream, as being able to setup the sound at the beginning fit what I was going for. Because of this, the inputs are greyed out once playback starts to inform the user that input changes are not supported during playback. In addition, to reduce the amount of CPU needed to play the sounds for long periods of time, right when playback starts if the lowpass filter is used a one-time transformation is made to the sound file selected. The resulting file is then played back over and over in a very simple way. This avoids needs to apply the filter continuously during playback. Allowing the filter or input to be adjusted on the fly would require re-computing the output file again.

Anyway, it is entirely possible to allow the inputs to be modified at will and have the played sounds be updated. It was just simpler to not worry about that for this app. I probably would not be interested in adding this ability, but if someone were interested in taking it on I could pull in their changes.

Back to your experience with the app, how successful did you find it in helping your baby sleep? Personally, I ended up not finding it that successful, but maybe my house is rather quiet or I was lucky and my son stays asleep on his own. (:

**Comment by klauf** [comment] 2017-07-28 12:26
Thanks for the detailed explanation! I haven't tried the low freq filter yet. Maybe without it it would be quicker to switch song and/or change timer? 

The Dryer works well when the baby is really tired but too excited to fall asleep on its own. Then 5 min dryer and it's done :) when it sleeps deeply I stop it, never used it during sleep. 
Hence the reason I wanted to adapt the timer 'on the fly', I turned it on without limit, and once the baby was asleep I wanted to leave it 5 min -> had to stop for like 1/4sec, so as to select the time and play; that was enough for the baby to wake up again!

**Comment by brarcher** [comment] 2017-08-02 19:16
At least the part of this issue relating to the timer should now be resolved in the latest release. Likely I'll not get to enabling switching of audio files during playback, though certainly if anyone were interested in contributing this change I could accept it. If the work done for the timer is sufficient for what you need, then I'll consider this issue resolved. If not, please re-open this issue.

**Closed by brarcher** 2017-08-02 19:16 UTC
Labels: enhancement, help wanted
