### ISSUE TITLE
Copy of your app on Google Play (Copyleft violation)

### ISSUE THREAD

**Issue by Poussinou** [brarcher/baby-sleep-sounds#71] opened 2018-04-07 18:33 UTC
Hi @brarcher 

I found [this app](https://play.google.com/store/apps/details?id=swagselfie.babysleepsounds) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by brarcher** [comment] 2018-04-08 02:37
Thanks for pointing that out. After downloading the app and testing it I agree that it is a near duplicate of my app, sound resources and all.

To be clear, the only concern I have with the app is its violation of the GPLv3. If someone did clone the app, change the name (as I probably own the rights to it) and provides the source, they can claim it as their own as long as the source code retains any copyright headers. In this case, I did not add any headers, so there is nothing to give attribution to if source was provided.

I've submitted a request to Google to have the app removed. In the past it took maybe a week or so for the process to go through.

**Comment by brarcher** [comment] 2018-04-08 02:39
Oh, I see you have reported many open source app clones on the Play Store in the past. How many have you found, and how wide spread is it? Also, thanks for fighting the good fight!

**Closed by brarcher** 2018-04-08 02:39 UTC

**Comment by Poussinou** [comment] 2018-04-08 12:27
I don't have any problem with forks, as long as they respect the GPL v3. (I already found copies of open source apps who were just copies with ads in it, but they provided the source code, so I took no actions against them simply because it was OK)
It takes more time today (more than a week I think, but every case is special, maybe you'll be lucky ;) ) and you will be asked to provide more information/screenshots...
I found hundreds of copies of open source apps, made by dozens of fake developers. Some of them are down today.

If you find another clone, please copy-paste the link here, it will help me to track fake developers
Thanks for your kind words ! ;)

**Comment by brarcher** [comment] 2018-04-12 02:33
I received a response from Google today. Interestingly, they rejected my request and choose to do nothing, but the app is no longer available on the store. Perhaps someone else issues a claim and it was taken down, or maybe the developer had second thoughts.
