### ISSUE TITLE
strange glitch

### ISSUE THREAD

**Issue by wolftune** [brarcher/baby-sleep-sounds#30] opened 2016-09-01 05:27 UTC
It may have just been my phone being weird somehow (probably unrelated, but it was about to have a dead battery), but just now I was running the app, all was good… Then, I came back after a while to hear the sound fading in and out every few seconds. The screen looked like nothing was playing. The play button said "play" not "stop", and the filter was unchecked. However, the sound was still going, just fading in and out, and still filtered. When I turned the filter back on and hit "play" everything went back to normal continuous nice sound…

**Comment by brarcher** [comment] 2016-09-01 13:16
> I came back after a while to hear the sound fading in and out every few seconds

Interesting.

There are two threads which will overlap in time to play the continuous audio. When one thread is almost done it wakes up the second thread to start playing. Similarly, when the second thread is almost done it wakes up the first, and so on. This should result in the two threads being separated in time. However, for some reason they are synchronizing.

I believe I have a solution for that, but want to better understand the problem. I'll run an experiment today and see if I can reproduce the issue locally.

> The play button said "play" not "stop", and the filter was unchecked.

Currently the app does not handle the case when Android tried to get the app to save its state when requested, perhaps before killing it due to low memory pressure. Though, if that were to happen, one would expect that playback would stop and not continue.... I'm not sure on this one yet, but I'll look into it. If you do see this again, could you grab the logs from the device and attach them so I can take a look?

**Comment by wolftune** [comment] 2016-09-01 14:26
Sure, I'll see about logs if this recurs. I may have to make my battery drain or something though. So far, been plugged in and working smoothly, loving the updated app…

**Comment by brarcher** [comment] 2016-09-02 02:12
I was able to reproduce this on my test phone by leaving it play all day. Indeed the two threads seem to synchronize over time. There may be small timing errors which collect the longer it runs, which tends to bring the threads closer in time rather than staying far apart.

This is why software is hard. Also math.

I have a potential fix for this. Instead of interlinking two threads which poke each other, a new thread will start each time that does not communicate with the first thread. This may be a bit wasteful (starting threads often), but should remove the synchronization. It can be improved later it if works.

I'll leave it run tomorrow and see if the issue manifests again. If not, I'll push it through.

**Comment by brarcher** [comment] 2016-09-03 02:46
I believe that this issue should now be resolved. The fix will appear in the next release, which has already been cut. In a day or so F-Droid will pick it up. If you are curious about the fix, take a look at referenced merge request above.

Each of the audio files were updated so that they each seamlessly loop into theirselves. I listened to them all and could not detect anything odd. If you happen to fine one which could be improved, please let me know.

And, thanks for the feedback!

**Closed by brarcher** 2016-09-03 02:46 UTC

**Comment by wolftune** [comment] 2016-09-03 03:49
Thanks!
